language: "node_js"
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  skip-cleanup: true
  domain: http://warm-partner.surge.sh
  project: ./build/

on:
  branch: master